### ISSUE TITLE
Estimate testing of linkset updates

### ISSUE THREAD

**Issue by stain** [openphacts/IdentityMappingService#24]
Idea:

We get some new linksets. 

* Q1: Do these links point to identifiers which exist in the in the RDF cache?
* Q2: Do the identifiers in the covered namespaces in RDF have corresponding links in IMS?
* Q3: What are the changes in the linksets? How many identifiers might give different results in IMS and from the API? (They can then be further inspected to see if changes are good or bad)

This task will estimate what is needed to build a simple test system for such queries.

**Comment by AlasdairGray** [comment]
We should also be considering 
* the context under which they are linking a pair of datasets
* overlap with existing linksets
* provenance (and implicitly the trust) of the linkset

**Comment by stain** [comment]
Not sure how to test the provenance except trying to download it again.. :-)

I was thinking a minimal thing, say one weeks effort, where a python script or something just picks 1000 random URIs from each linksets and tests them against IMS (they should all work), and against a couple of the 1.5 API (and 2.0 dev) methods.

Exactly which API methods are relevant for which linkset might need to be customized due to type mismatch (e.g. a disase URI would not work well on target info), this should be obvious after running the test and see which linkset gives 0 hits on all API calls.

**Comment by AlasdairGray** [comment]
There was an idea of typing the data source on each side of a linkset, but I think very few (if any) of our linksets do this.

**Comment by stain** [comment]
Started on a prototype on https://github.com/openphacts/ops-linkset-testing that samples 1000 from each. Not quite in a runnable state right now.. but it seems doable in a week, so I'll leave that as the estimate.

**Comment by Chris-Evelo** [comment]
Yes.. But actually the linkset itself need not come from any of the two sides.

Chris
—
Prof.Dr. Chris Evelo
Dept. Head Bioinformatics – BiGCaT
Maastricht University

**Comment by AlasdairGray** [comment]
@Chris-Evelo I think you misunderstood what I meant. 

A linkset connects a source and a target. In the OPS specification we suggest that the type of data that is being connected on each side is typed using bdb:sourceType and bdb:targetType where the type would be chemical, protein, etc. (Note that those might not be the exact predicates, it is a long time since I looked at that.) This is independent of who is providing the linkset, it is merely a declaration along with the linkset justification to give the IMS more information to reason with.

**Comment by Chris-Evelo** [comment]
Thanks @AlasdairGray, I misunderstood that indeed.
